<<<<<<< HEAD
<<<<<<< HEAD
---
title: "LUC_Project"
author: "Scott Spillias"
date: "24/11/2020"
output: pdf_document
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "images/",
  dev = c('pdf')
)
```

```{r}
library(tidyverse)
library(readxl)
library(reshape2)
library(gam)
library(forecast)
library(fable)
library(fabletools)
library(tsibble)
library(lubridate)
library(tis)
library(ggpubr)
#library(LaCroixColoR)
library(ggsci)
library(stats)
library(feasts)
library(broom)

```


```{r import FAO Data}

FAO_Data <- read_excel("FAO_Data.xlsx", 
    sheet = "Sheet2")
FAO_Data <- FAO_Data[!is.na(FAO_Data$Header),]

```

```{r Seaweed Report Data}
lis <- split(FAO_Data,FAO_Data$...1,drop = TRUE)
lis <- lapply(lis, function(x) x[-1,-1])
names(lis) <- sapply(sapply(lis, "[[",1),"[",1)
lis <- lapply(lis, function(x) x[-1,])
lis <- lapply(lis, function(x) setNames(x, x[1,]))
lis <- lapply(lis, function(x) x[-1,])

```

```{r}
# What is the unit price of each end-use? Does it vary across countries? Is this already in the report?

#Weights are in tonnes...DW? FW?

# Big Question: How much seaweed (and what type) will the world (by country) produce in 2050?
## Use models of uncertainty to estimate? Treat industry as a biological species. Examine growth rates in the context of resources need for growth and survival. 
## Step One: Calculate growth rates for each country / Fit a model for each country.
## Step Two: Identify sources of possible variation in each country model.
```


```{r}
### Set Important Parameters
# Baseline number of years over which to assign 'median' to compare against
bsln <- 7
# Minimum production value below which countries are removed 
min_production <- 1
# Percentage loss below which a 'shock occurs'
perc_thresh <- -0.2
# Colour Scheme
cbPalette <- c("#F00011", "#CC79A7", "#56B4E9", "#F0E442","#009E73", "#0072B2", "#E69F00","#D55E00")

```

```{r}
## IMPORT AND clean DATA
groups <- read_csv("CL_FI_SPECIES_GROUPS.csv")
env <- read_csv("CL_FI_ENVIRONMENT.csv")
country <- read_csv("CL_FI_COUNTRY_GROUPS.csv")
Rich_Shock_DATA <-  read_xlsx("Rich_Shock_DATA.xlsx")
FAO_raw <- read_csv("TS_FI_AQUACULTURE.csv") %>% 
  merge(.,groups, by.x = "SPECIES", by.y = "3Alpha_Code" ) %>% 
  merge(., country, by.x = "COUNTRY", by.y = "UN_Code")
FAO_raw$Name_En.y[FAO_raw$Name_En.y == "Un. Sov. Soc. Rep."] <- "Russian Federation"
FAO_raw <- FAO_raw %>% 
  merge(., Rich_Shock_DATA, unique(Rich_Shock_DATA[,c(2,10,11)]), by.x = "Name_En.y", by.y = "Country", all.x = TRUE) %>% 
  filter(ENVIRONMENT == "3") %>% 
  filter(Major_Group == "PLANTAE AQUATICAE") %>% 
  filter(YEAR > 1970) %>% 
  mutate(Genus = word(Scientific_Name,1)) %>% 
  rename(Country = Name_En.y) %>% 
  select(Country, Genus, YEAR, QUANTITY, VALUE, Region, SubRegion)
 FAO_raw <- filter(FAO_raw,!are_duplicated(FAO_raw, index= YEAR, key = c("Genus", "Country", "QUANTITY", "VALUE"))) %>% 
   mutate(PRICE = VALUE/QUANTITY)
           
```

```{r}
## Group data according to 'Metric' field, by Year, Genus, and Country


FAO_met <- FAO_raw %>% 
  mutate(Metric = QUANTITY) %>%  ### Choose HERE: VALUE, QUANTITY, PRICE
  select(-VALUE, -QUANTITY, -PRICE) %>% 
  group_by(Genus,Country, YEAR, Region, SubRegion) %>% 
  summarize(Metric = sum(Metric, na.rm = TRUE)) %>% 
  as_tsibble(index = YEAR, key = c("Genus", "Country", "Region", "SubRegion"))

sw_agg <- FAO_met  %>% 
  fill_gaps(.full = TRUE) %>% 
  aggregate_key((Country/SubRegion/Region)*Genus, Metric = sum(Metric, na.rm = TRUE)) 

scan_gaps(sw_agg)


sw_agg %>% as_tsibble() %>% 
  filter(is_aggregated(Country), !is_aggregated(Genus)) %>%
  autoplot(Metric) +
  theme(legend.position = "none")+
   scale_y_log10(limits = c(1,1e8), expand = c(0, 0))
```

```{r}
fit <- sw_agg %>% 
  filter(YEAR<=2018) %>% 
  model(ETS = ETS(Metric),
        ARIMA = ARIMA(Metric)) %>% 
  reconcile(bu_E = bottom_up(ETS),
            ols_E = min_trace(ETS, method = "ols"),
            bu_A = bottom_up(ARIMA),
            ols_A = min_trace(ARIMA, method = "ols")
           # mint = min_trace(base, method = "mint_shrink")
           )
fc <- fit %>% forecast(h = "30 years")

fc %>% 
  filter(!is_aggregated(Country), is_aggregated(Genus)) %>% 
  filter(Region == "East Asia") %>% 
  filter(!(.model %in% c("ols_E", "ols_A"))) %>% 
  autoplot(
    sw_agg %>% filter(YEAR>=1980), alpha = 0.7, level = 70) +
  facet_wrap(vars(Country), scales = "free_y"
  )

fc %>% filter(is_aggregated(Region), is_aggregated(Genus)) %>% 
  accuracy(
    data = sw_agg, 
    measures = list(rmse = RMSE, mase = MASE)
  ) %>% 
  group_by(.model) %>% 
  summarise(rmse = mean(rmse), mase = mean(mase))
  
  
```


```{r}
# Examine for Stationarity
tc = "EuCA"
sp = "Phaeophyceae"

sw %>% filter(Location == tc, Genus == sp) %>% 
  autoplot(Metric)

t_sw <- sw %>% filter(Location == tc, Genus == sp)

t_sw %>% 
  mutate(diff_Metric = difference(difference(Metric))) %>% 
  features(diff_Metric, ljung_box, lag = 1)

lambda <- t_sw %>%  
  features(Metric, features = guerrero) %>% 
  pull(lambda_guerrero)

t_sw %>% 
gg_tsdisplay(difference(difference(box_cox(Metric, lambda))), plot_type = 'partial')


```


```{r Explore models}
##Safer to use stochastic trends for longer forecast horizons
t_sw_fit <- t_sw %>% 
  mutate(Metric = box_cox(Metric, lambda)) %>% 
  model(
  arima210 = ARIMA(Metric ~ pdq(2,1,0)),
    arima011 = ARIMA(Metric ~ pdq(0,1,1)),
    stepwise = ARIMA(Metric),
    search = ARIMA(Metric, stepwise = FALSE)
    
  )
## Want smallest AICc
glance(t_sw_fit) %>% slice_max(AICc, n = 1, with_ties = FALSE)

## Want all criteria met
t_sw_fit %>% 
  select(search) %>% 
  gg_tsresiduals()

## Want large p-value
augment(t_sw_fit) %>%
  filter(.model=='search') %>%
  features(.innov, ljung_box, lag = 10, dof = 3)

t_sw_fit %>%
  forecast(h=32) %>%
  filter(.model=='search') %>% 
  autoplot(t_sw)


t_sw <- t_sw %>% mutate(Metric = box_cox(Metric, lambda)) %>% 
  slice(-n()) %>% 
  stretch_tsibble(.init = 10) %>% 
  mutate(Metric = box_cox(Metric, lambda)) %>% 
  model(
    stepwise = ARIMA(Metric),
    ETS = ETS(Metric)
    
  ) %>% 
  forecast(h = 1) %>% 
  accuracy(t_sw)
```

```{r Fit models}
sw_gts <- sw %>% 
  aggregate_key(Location*Genus)

lambda <- sw %>% group_by(Genus, Location) %>% 
  features(Metric, features = guerrero) 
fit <- merge(sw, lambda, by = c("Genus", "Location")) %>% 
  mutate(Metric = box_cox(Metric, lambda_guerrero)) %>% 
  group_by(Genus, Location) %>% 
  nest() %>% 
  mutate(model = map(data, function(Metric) ARIMA(Metric, stepwise = FALSE)))

fcast <- fit %>% 
  mutate(fcast = map(model, predict))#forecast(h = "32 years", data = model)))
    
 


              
      arima210 = ARIMA(Metric ~ pdq(2,1,0), data = .x),
      arima011 = ARIMA(Metric ~ pdq(0,1,1),data = .x),
      stepwise = ARIMA(Metric, data = .x),
      search = ARIMA(Metric, stepwise = FALSE, data = .x)
      ))# %>% 
## Want smallest AICc
glance(t_sw_fit) %>% slice_max(AICc, n = 1, with_ties = FALSE))

fit <- sw %>% 
  model(ARIMA(box_cox(Metric, lambda))) # this is for ETS-> ~ error("M") + trend("A") + season("N")
            
t_fit <- fit %>% filter(Location == tc, Genus == sp)


# Compute forecasts
fcast <- forecast(fit, h = "32 years", level = 5) %>% 
  arrange(Genus, Location)

sw$lambda_guerrero


t_fcast <- fcast %>% filter(Location == tc, Genus == sp) 


t_fcast %>% 
autoplot() + 
  geom_line(aes(y = Metric, col = "Data", group = Location), data = t_sw)

t_fit %>% forecast(h = "32 years") %>% autoplot(t_sw)

```




```{r}
## Diagnostics
# Plot Residuals
aug <- augment(t_fit) 
autoplot(aug, .innov) +
  labs(title = "Plot of residuals")
aug %>%  features(.innov, box_pierce, lag = 10, dof =2)
aug %>% features(.innov, ljung_box, lag = 10, dof =2)

## Histogram
aug %>% ggplot(aes(x = .innov)) +
  geom_histogram() +
  labs(title = "Histogram of residuals")

t_fit %>% 
  gg_tsresiduals()

  
report(fit %>% filter(Location == tc, Genus == sp))
#components(fit %>% filter(Location == tc, Genus == sp)) %>%
 # autoplot() +
 # labs(title = "ETS(M,N,M) components")
  
```


```{r}


#fcast %>% filter(Location == tc) %>% 
#autoplot(sw) + 
#  theme(legend.position = "none") + 
#    scale_y_log10(limits = c(1,1e8), expand = c(0, 0))
ggplot(fcast %>% filter(Location == tc)
       ,
       aes(x=YEAR, y=Metric, fill = Location)) +
  autolayer(fcast %>% filter(Location == tc), alpha = 0.2, .vars = .mean, fcol = "black") +
  geom_line(data = sw %>% filter(Location == tc), aes(x = YEAR, y = Metric, group = Genus)) +
 #facet_wrap(~ Location, scales = "free") + 
    scale_y_log10(limits = c(1,1e8), expand = c(0, 0)) +
  theme(legend.position = "none") 
```

```{r}
fcast_2050 <- fcast %>% filter(YEAR == 2050)
```


```{r}
##Split countries into separate dataframes of Years by species  
listdata <- split(main_df, main_df$Country, drop = TRUE) 

listdata_val <- lapply(listdata, function(x) 
  as.data.frame(
    dcast(x, YEAR ~ Genus, 
          value.var = "VALUE", fun.aggregate = sum))) 

listdata_qua <- lapply(listdata, function(x) 
  as.data.frame(
    dcast(x, YEAR ~ Genus, 
          value.var = "QUANTITY", fun.aggregate = sum)))
```


```{r Choose _val or _qua}
##
listdata <- listdata_qua

```

```{r}
#### Remove Unwanted time-series from list of dataframes
## Remove time-series with fewer non-zero values than baseline (bsln)
#listdata <- lapply(listdata, function(x) {
# as.data.frame(x[, unlist((lapply(x, function(y) {sum(y > 0, na.rm = TRUE) #> bsln}))) ] )
#})

## Remove time-series with low production values; mean is below min_production (specified at start)
#listdata <- lapply(listdata, function(x) {
#  as.data.frame(x[, unlist((lapply(x, function(y) {mean(y, na.rm = TRUE) > min_production}))) ] )
#})

## Remove Countries with 2 or fewer cultivated species and countries with fewer reported years than bsln
#listdata <- listdata[sapply(listdata, function(x) ncol(x)) > 2]  
#listdata <- listdata[lapply(listdata, function(x) nrow(x)) > bsln]

```

```{r}
## In list of dataframes, set Years column to be row.names 
for (i in 1:length(listdata)) {
 row.names(listdata[[i]]) = listdata[[i]][,1]}

#listdata <- lapply(listdata, function(x) as.data.frame(x[,-1]))
```

```{r}
#### IDENTIFY SHOCKS
## FIT GAM MODELs 

models_ga <- listdata

models_ga <- lapply(listdata, function(x) {lapply(x, function(a,b)
  gam(a ~ lo(as.numeric(row.names(b)))),
  b = x)})
```

```{r}
## Fit LOESS Models (if desired)
models_ls <- listdata
models_ls <- lapply(listdata, function(x) {lapply(x, function(a,b) 
  loess(a ~ as.numeric(row.names(b)), 
        span = 0.6, na.action = "na.omit"), b=x)})
```



```{r Time-Series Visualization}

## Visualization of time-series for specific Case Studies
## ## this can be used to double-check that shocks are well-defined
## ## tc = Country name ; sp = Genus name

tc <- "China"
sp <- "Laminaria"

case_y = as.data.frame(
  cbind(
    as.numeric(
     row.names(
    listdata[[tc]][!is.na(
       listdata[[tc]][[sp]])
      ,])
   )
  , 
                    predict(models_ga[[tc]][[sp]] ) ))

names(case_y) <- c("YEAR", "Value")

case_x <- as.data.frame(cbind(as.numeric(row.names(listdata[[tc]][!is.na(listdata[[tc]][[sp]]),])), predict(models_ls[[tc]][[sp]]) ))
names(case_x) <- c("Year", "Value")


p <- ggplot() + 
  ## GAM Model Fit
  geom_line(data=case_y, aes(x=YEAR, y=Value), color='blue') + 
  ## LOESS Model Fit
  geom_line(data=case_x, aes(x=Year, y=Value), color='orange') + 
  ## DataPoints
  geom_line(data = listdata[[tc]], aes(x = as.numeric(row.names(listdata[[tc]])), 
                                     y = listdata[[tc]][[sp]]), na.rm = T) +
  xlim(1960,2050)
p
```

```{r}
prediction <- as_tsibble(as.data.frame(cbind(as.numeric(row.names(listdata[[tc]])),                            listdata[[tc]][[sp]])), index = "V1") %>% 
  rename("Year"= "V1" , "Amount" = "V2") 
prediction <- prediction %>% 
  model(
    #arima = ARIMA(Amount),
    ets = ETS(box_cox(Amount, 0.3))
    ) %>%
  forecast(h = "33 years", level = 5) 
p + geom_line(data = prediction, aes(x = Year, y = .mean, color = "red"))

growth <-  prediction %>%
  rename("Value" = ".mean") %>% 
  select(Year, Value) %>% 
  # first sort by year
  arrange(Year) %>%
  mutate(Diff_year = Year - lag(Year),  # Difference in time (just in case there are gaps)
         Diff_growth = Value - lag(Value), # Difference in route between years
         Rate_percent = (Diff_growth / Diff_year)/Value * 100) 

print(mean(growth[-1,]$Rate_percent))
###Need to get growth rate for each species for each country. Build into list.

```


```{r}
g_rates <- lapply(listdata, function(x) add_column(x, row.names(x), .before = 1)) %>% 
melt() %>% 
  rename("Year" = "row.names(x)", "Genus" = "variable", "Country" = "L1", "Value" = "value")  %>% 
  mutate(Country = as.factor(Country),
         Year = as.numeric(Year)) 
  

g_rates <- as.data.frame(g_rates)

```

||||||| e6cda0e
---
title: "LUC_Project"
author: "Scott Spillias"
date: "24/11/2020"
output: pdf_document
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "images/",
  dev = c('pdf')
)
```

```{r}
library(tidyverse)
library(readxl)
library(reshape2)
library(gam)
library(forecast)
library(fable)
library(fabletools)
library(tsibble)
library(lubridate)
library(tis)
library(ggpubr)
#library(LaCroixColoR)
library(ggsci)
library(stats)
library(feasts)
library(broom)

test
```


```{r import FAO Data}

FAO_Data <- read_excel("FAO_Data.xlsx", 
    sheet = "Sheet2")
FAO_Data <- FAO_Data[!is.na(FAO_Data$Header),]

```

```{r Seaweed Report Data}
lis <- split(FAO_Data,FAO_Data$...1,drop = TRUE)
lis <- lapply(lis, function(x) x[-1,-1])
names(lis) <- sapply(sapply(lis, "[[",1),"[",1)
lis <- lapply(lis, function(x) x[-1,])
lis <- lapply(lis, function(x) setNames(x, x[1,]))
lis <- lapply(lis, function(x) x[-1,])

```

```{r}
# What is the unit price of each end-use? Does it vary across countries? Is this already in the report?

#Weights are in tonnes...DW? FW?

# Big Question: How much seaweed (and what type) will the world (by country) produce in 2050?
## Use models of uncertainty to estimate? Treat industry as a biological species. Examine growth rates in the context of resources need for growth and survival. 
## Step One: Calculate growth rates for each country / Fit a model for each country.
## Step Two: Identify sources of possible variation in each country model.
```


```{r}
### Set Important Parameters
# Baseline number of years over which to assign 'median' to compare against
bsln <- 7
# Minimum production value below which countries are removed 
min_production <- 1
# Percentage loss below which a 'shock occurs'
perc_thresh <- -0.2
# Colour Scheme
cbPalette <- c("#F00011", "#CC79A7", "#56B4E9", "#F0E442","#009E73", "#0072B2", "#E69F00","#D55E00")

```

```{r}
## IMPORT AND clean DATA
groups <- read_csv("CL_FI_SPECIES_GROUPS.csv")
env <- read_csv("CL_FI_ENVIRONMENT.csv")
country <- read_csv("CL_FI_COUNTRY_GROUPS.csv")
Rich_Shock_DATA <-  read_xlsx("Rich_Shock_DATA.xlsx")
FAO_raw <- read_csv("TS_FI_AQUACULTURE.csv") %>% 
  merge(.,groups, by.x = "SPECIES", by.y = "3Alpha_Code" ) %>% 
  merge(., country, by.x = "COUNTRY", by.y = "UN_Code")
FAO_raw$Name_En.y[FAO_raw$Name_En.y == "Un. Sov. Soc. Rep."] <- "Russian Federation"
FAO_raw <- FAO_raw %>% 
  merge(., Rich_Shock_DATA, unique(Rich_Shock_DATA[,c(2,10,11)]), by.x = "Name_En.y", by.y = "Country", all.x = TRUE) %>% 
  filter(ENVIRONMENT == "3") %>% 
  filter(Major_Group == "PLANTAE AQUATICAE") %>% 
  filter(YEAR > 1970) %>% 
  mutate(Genus = word(Scientific_Name,1)) %>% 
  rename(Country = Name_En.y) %>% 
  select(Country, Genus, YEAR, QUANTITY, VALUE, Region, SubRegion)
 FAO_raw <- filter(FAO_raw,!are_duplicated(FAO_raw, index= YEAR, key = c("Genus", "Country", "QUANTITY", "VALUE"))) %>% 
   mutate(PRICE = VALUE/QUANTITY)
           
```

```{r}
## Group data according to 'Metric' field, by Year, Genus, and Country


FAO_met <- FAO_raw %>% 
  mutate(Metric = QUANTITY) %>%  ### Choose HERE: VALUE, QUANTITY, PRICE
  select(-VALUE, -QUANTITY, -PRICE) %>% 
  group_by(Genus,Country, YEAR, Region, SubRegion) %>% 
  summarize(Metric = sum(Metric, na.rm = TRUE)) %>% 
  as_tsibble(index = YEAR, key = c("Genus", "Country", "Region", "SubRegion"))

sw_agg <- FAO_met  %>% 
  fill_gaps(.full = TRUE) %>% 
  aggregate_key((Country/SubRegion/Region)*Genus, Metric = sum(Metric, na.rm = TRUE)) 

scan_gaps(sw_agg)


sw_agg %>% as_tsibble() %>% 
  filter(is_aggregated(Country), !is_aggregated(Genus)) %>%
  autoplot(Metric) +
  theme(legend.position = "none")+
   scale_y_log10(limits = c(1,1e8), expand = c(0, 0))
```

```{r}
fit <- sw_agg %>% 
  filter(YEAR<=2018) %>% 
  model(ETS = ETS(Metric),
        ARIMA = ARIMA(Metric)) %>% 
  reconcile(bu_E = bottom_up(ETS),
            ols_E = min_trace(ETS, method = "ols"),
            bu_A = bottom_up(ARIMA),
            ols_A = min_trace(ARIMA, method = "ols")
           # mint = min_trace(base, method = "mint_shrink")
           )
fc <- fit %>% forecast(h = "30 years")

fc %>% 
  filter(!is_aggregated(Country), is_aggregated(Genus)) %>% 
  filter(Region == "East Asia") %>% 
  filter(!(.model %in% c("ols_E", "ols_A"))) %>% 
  autoplot(
    sw_agg %>% filter(YEAR>=1980), alpha = 0.7, level = 70) +
  facet_wrap(vars(Country), scales = "free_y"
  )

fc %>% filter(is_aggregated(Region), is_aggregated(Genus)) %>% 
  accuracy(
    data = sw_agg, 
    measures = list(rmse = RMSE, mase = MASE)
  ) %>% 
  group_by(.model) %>% 
  summarise(rmse = mean(rmse), mase = mean(mase))
  
  
```


```{r}
# Examine for Stationarity
tc = "EuCA"
sp = "Phaeophyceae"

sw %>% filter(Location == tc, Genus == sp) %>% 
  autoplot(Metric)

t_sw <- sw %>% filter(Location == tc, Genus == sp)

t_sw %>% 
  mutate(diff_Metric = difference(difference(Metric))) %>% 
  features(diff_Metric, ljung_box, lag = 1)

lambda <- t_sw %>%  
  features(Metric, features = guerrero) %>% 
  pull(lambda_guerrero)

t_sw %>% 
gg_tsdisplay(difference(difference(box_cox(Metric, lambda))), plot_type = 'partial')


```


```{r Explore models}
##Safer to use stochastic trends for longer forecast horizons
t_sw_fit <- t_sw %>% 
  mutate(Metric = box_cox(Metric, lambda)) %>% 
  model(
  arima210 = ARIMA(Metric ~ pdq(2,1,0)),
    arima011 = ARIMA(Metric ~ pdq(0,1,1)),
    stepwise = ARIMA(Metric),
    search = ARIMA(Metric, stepwise = FALSE)
    
  )
## Want smallest AICc
glance(t_sw_fit) %>% slice_max(AICc, n = 1, with_ties = FALSE)

## Want all criteria met
t_sw_fit %>% 
  select(search) %>% 
  gg_tsresiduals()

## Want large p-value
augment(t_sw_fit) %>%
  filter(.model=='search') %>%
  features(.innov, ljung_box, lag = 10, dof = 3)

t_sw_fit %>%
  forecast(h=32) %>%
  filter(.model=='search') %>% 
  autoplot(t_sw)


t_sw <- t_sw %>% mutate(Metric = box_cox(Metric, lambda)) %>% 
  slice(-n()) %>% 
  stretch_tsibble(.init = 10) %>% 
  mutate(Metric = box_cox(Metric, lambda)) %>% 
  model(
    stepwise = ARIMA(Metric),
    ETS = ETS(Metric)
    
  ) %>% 
  forecast(h = 1) %>% 
  accuracy(t_sw)
```

```{r Fit models}
sw_gts <- sw %>% 
  aggregate_key(Location*Genus)

lambda <- sw %>% group_by(Genus, Location) %>% 
  features(Metric, features = guerrero) 
fit <- merge(sw, lambda, by = c("Genus", "Location")) %>% 
  mutate(Metric = box_cox(Metric, lambda_guerrero)) %>% 
  group_by(Genus, Location) %>% 
  nest() %>% 
  mutate(model = map(data, function(Metric) ARIMA(Metric, stepwise = FALSE)))

fcast <- fit %>% 
  mutate(fcast = map(model, predict))#forecast(h = "32 years", data = model)))
    
 


              
      arima210 = ARIMA(Metric ~ pdq(2,1,0), data = .x),
      arima011 = ARIMA(Metric ~ pdq(0,1,1),data = .x),
      stepwise = ARIMA(Metric, data = .x),
      search = ARIMA(Metric, stepwise = FALSE, data = .x)
      ))# %>% 
## Want smallest AICc
glance(t_sw_fit) %>% slice_max(AICc, n = 1, with_ties = FALSE))

fit <- sw %>% 
  model(ARIMA(box_cox(Metric, lambda))) # this is for ETS-> ~ error("M") + trend("A") + season("N")
            
t_fit <- fit %>% filter(Location == tc, Genus == sp)


# Compute forecasts
fcast <- forecast(fit, h = "32 years", level = 5) %>% 
  arrange(Genus, Location)

sw$lambda_guerrero


t_fcast <- fcast %>% filter(Location == tc, Genus == sp) 


t_fcast %>% 
autoplot() + 
  geom_line(aes(y = Metric, col = "Data", group = Location), data = t_sw)

t_fit %>% forecast(h = "32 years") %>% autoplot(t_sw)

```




```{r}
## Diagnostics
# Plot Residuals
aug <- augment(t_fit) 
autoplot(aug, .innov) +
  labs(title = "Plot of residuals")
aug %>%  features(.innov, box_pierce, lag = 10, dof =2)
aug %>% features(.innov, ljung_box, lag = 10, dof =2)

## Histogram
aug %>% ggplot(aes(x = .innov)) +
  geom_histogram() +
  labs(title = "Histogram of residuals")

t_fit %>% 
  gg_tsresiduals()

  
report(fit %>% filter(Location == tc, Genus == sp))
#components(fit %>% filter(Location == tc, Genus == sp)) %>%
 # autoplot() +
 # labs(title = "ETS(M,N,M) components")
  
```


```{r}


#fcast %>% filter(Location == tc) %>% 
#autoplot(sw) + 
#  theme(legend.position = "none") + 
#    scale_y_log10(limits = c(1,1e8), expand = c(0, 0))
ggplot(fcast %>% filter(Location == tc)
       ,
       aes(x=YEAR, y=Metric, fill = Location)) +
  autolayer(fcast %>% filter(Location == tc), alpha = 0.2, .vars = .mean, fcol = "black") +
  geom_line(data = sw %>% filter(Location == tc), aes(x = YEAR, y = Metric, group = Genus)) +
 #facet_wrap(~ Location, scales = "free") + 
    scale_y_log10(limits = c(1,1e8), expand = c(0, 0)) +
  theme(legend.position = "none") 
```

```{r}
fcast_2050 <- fcast %>% filter(YEAR == 2050)
```


```{r}
##Split countries into separate dataframes of Years by species  
listdata <- split(main_df, main_df$Country, drop = TRUE) 

listdata_val <- lapply(listdata, function(x) 
  as.data.frame(
    dcast(x, YEAR ~ Genus, 
          value.var = "VALUE", fun.aggregate = sum))) 

listdata_qua <- lapply(listdata, function(x) 
  as.data.frame(
    dcast(x, YEAR ~ Genus, 
          value.var = "QUANTITY", fun.aggregate = sum)))
```


```{r Choose _val or _qua}
##
listdata <- listdata_qua

```

```{r}
#### Remove Unwanted time-series from list of dataframes
## Remove time-series with fewer non-zero values than baseline (bsln)
#listdata <- lapply(listdata, function(x) {
# as.data.frame(x[, unlist((lapply(x, function(y) {sum(y > 0, na.rm = TRUE) #> bsln}))) ] )
#})

## Remove time-series with low production values; mean is below min_production (specified at start)
#listdata <- lapply(listdata, function(x) {
#  as.data.frame(x[, unlist((lapply(x, function(y) {mean(y, na.rm = TRUE) > min_production}))) ] )
#})

## Remove Countries with 2 or fewer cultivated species and countries with fewer reported years than bsln
#listdata <- listdata[sapply(listdata, function(x) ncol(x)) > 2]  
#listdata <- listdata[lapply(listdata, function(x) nrow(x)) > bsln]

```

```{r}
## In list of dataframes, set Years column to be row.names 
for (i in 1:length(listdata)) {
 row.names(listdata[[i]]) = listdata[[i]][,1]}

#listdata <- lapply(listdata, function(x) as.data.frame(x[,-1]))
```

```{r}
#### IDENTIFY SHOCKS
## FIT GAM MODELs 

models_ga <- listdata

models_ga <- lapply(listdata, function(x) {lapply(x, function(a,b)
  gam(a ~ lo(as.numeric(row.names(b)))),
  b = x)})
```

```{r}
## Fit LOESS Models (if desired)
models_ls <- listdata
models_ls <- lapply(listdata, function(x) {lapply(x, function(a,b) 
  loess(a ~ as.numeric(row.names(b)), 
        span = 0.6, na.action = "na.omit"), b=x)})
```



```{r Time-Series Visualization}

## Visualization of time-series for specific Case Studies
## ## this can be used to double-check that shocks are well-defined
## ## tc = Country name ; sp = Genus name

tc <- "China"
sp <- "Laminaria"

case_y = as.data.frame(
  cbind(
    as.numeric(
     row.names(
    listdata[[tc]][!is.na(
       listdata[[tc]][[sp]])
      ,])
   )
  , 
                    predict(models_ga[[tc]][[sp]] ) ))

names(case_y) <- c("YEAR", "Value")

case_x <- as.data.frame(cbind(as.numeric(row.names(listdata[[tc]][!is.na(listdata[[tc]][[sp]]),])), predict(models_ls[[tc]][[sp]]) ))
names(case_x) <- c("Year", "Value")


p <- ggplot() + 
  ## GAM Model Fit
  geom_line(data=case_y, aes(x=YEAR, y=Value), color='blue') + 
  ## LOESS Model Fit
  geom_line(data=case_x, aes(x=Year, y=Value), color='orange') + 
  ## DataPoints
  geom_line(data = listdata[[tc]], aes(x = as.numeric(row.names(listdata[[tc]])), 
                                     y = listdata[[tc]][[sp]]), na.rm = T) +
  xlim(1960,2050)
p
```

```{r}
prediction <- as_tsibble(as.data.frame(cbind(as.numeric(row.names(listdata[[tc]])),                            listdata[[tc]][[sp]])), index = "V1") %>% 
  rename("Year"= "V1" , "Amount" = "V2") 
prediction <- prediction %>% 
  model(
    #arima = ARIMA(Amount),
    ets = ETS(box_cox(Amount, 0.3))
    ) %>%
  forecast(h = "33 years", level = 5) 
p + geom_line(data = prediction, aes(x = Year, y = .mean, color = "red"))

growth <-  prediction %>%
  rename("Value" = ".mean") %>% 
  select(Year, Value) %>% 
  # first sort by year
  arrange(Year) %>%
  mutate(Diff_year = Year - lag(Year),  # Difference in time (just in case there are gaps)
         Diff_growth = Value - lag(Value), # Difference in route between years
         Rate_percent = (Diff_growth / Diff_year)/Value * 100) 

print(mean(growth[-1,]$Rate_percent))
###Need to get growth rate for each species for each country. Build into list.

```


```{r}
g_rates <- lapply(listdata, function(x) add_column(x, row.names(x), .before = 1)) %>% 
melt() %>% 
  rename("Year" = "row.names(x)", "Genus" = "variable", "Country" = "L1", "Value" = "value")  %>% 
  mutate(Country = as.factor(Country),
         Year = as.numeric(Year)) 
  

g_rates <- as.data.frame(g_rates)

```

=======
---
title: "LUC_Project"
author: "Scott Spillias"
date: "24/11/2020"
output: pdf_document
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "images/",
  dev = c('pdf')
)
```

```{r}
library(tidyverse)
library(readxl)
library(reshape2)
library(gam)
library(forecast)
library(fable)
library(fabletools)
library(tsibble)
library(lubridate)
library(tis)
library(ggpubr)
#library(LaCroixColoR)
library(ggsci)
library(stats)
library(feasts)
library(broom)

```


```{r import FAO Data}

FAO_Data <- read_excel("FAO_Data.xlsx", 
    sheet = "Sheet2")
FAO_Data <- FAO_Data[!is.na(FAO_Data$Header),]

```

```{r Seaweed Report Data}
lis <- split(FAO_Data,FAO_Data$...1,drop = TRUE)
lis <- lapply(lis, function(x) x[-1,-1])
names(lis) <- sapply(sapply(lis, "[[",1),"[",1)
lis <- lapply(lis, function(x) x[-1,])
lis <- lapply(lis, function(x) setNames(x, x[1,]))
lis <- lapply(lis, function(x) x[-1,])

```

```{r}
# What is the unit price of each end-use? Does it vary across countries? Is this already in the report?

#Weights are in tonnes...DW? FW?

# Big Question: How much seaweed (and what type) will the world (by country) produce in 2050?
## Use models of uncertainty to estimate? Treat industry as a biological species. Examine growth rates in the context of resources need for growth and survival. 
## Step One: Calculate growth rates for each country / Fit a model for each country.
## Step Two: Identify sources of possible variation in each country model.
```


```{r}
### Set Important Parameters
# Baseline number of years over which to assign 'median' to compare against
bsln <- 7
# Minimum production value below which countries are removed 
min_production <- 1
# Percentage loss below which a 'shock occurs'
perc_thresh <- -0.2
# Colour Scheme
cbPalette <- c("#F00011", "#CC79A7", "#56B4E9", "#F0E442","#009E73", "#0072B2", "#E69F00","#D55E00")

```

```{r}
## IMPORT AND clean DATA
groups <- read_csv("CL_FI_SPECIES_GROUPS.csv")
env <- read_csv("CL_FI_ENVIRONMENT.csv")
country <- read_csv("CL_FI_COUNTRY_GROUPS.csv")
Rich_Shock_DATA <-  read_xlsx("Rich_Shock_DATA.xlsx")
FAO_raw <- read_csv("TS_FI_AQUACULTURE.csv") %>% 
  merge(.,groups, by.x = "SPECIES", by.y = "3Alpha_Code" ) %>% 
  merge(., country, by.x = "COUNTRY", by.y = "UN_Code")
FAO_raw$Name_En.y[FAO_raw$Name_En.y == "Un. Sov. Soc. Rep."] <- "Russian Federation"
FAO_raw <- FAO_raw %>% 
  merge(., Rich_Shock_DATA, unique(Rich_Shock_DATA[,c(2,10,11)]), by.x = "Name_En.y", by.y = "Country", all.x = TRUE) %>% 
  filter(ENVIRONMENT == "3") %>% 
  filter(Major_Group == "PLANTAE AQUATICAE") %>% 
  filter(YEAR > 1970) %>% 
  mutate(Genus = word(Scientific_Name,1)) %>% 
  rename(Country = Name_En.y) %>% 
  select(Country, Genus, YEAR, QUANTITY, VALUE, Region, SubRegion)
 FAO_raw <- filter(FAO_raw,!are_duplicated(FAO_raw, index= YEAR, key = c("Genus", "Country", "QUANTITY", "VALUE"))) %>% 
   mutate(PRICE = VALUE/QUANTITY)
           
```

```{r}
## Group data according to 'Metric' field, by Year, Genus, and Country


FAO_met <- FAO_raw %>% 
  mutate(Metric = QUANTITY) %>%  ### Choose HERE: VALUE, QUANTITY, PRICE
  select(-VALUE, -QUANTITY, -PRICE) %>% 
  group_by(Genus,Country, YEAR, Region, SubRegion) %>% 
  summarize(Metric = sum(Metric, na.rm = TRUE)) %>% 
  as_tsibble(index = YEAR, key = c("Genus", "Country", "Region", "SubRegion"))

sw_agg <- FAO_met  %>% 
  fill_gaps(.full = TRUE) %>% 
  aggregate_key((Country/SubRegion/Region)*Genus, Metric = sum(Metric, na.rm = TRUE)) 

scan_gaps(sw_agg)


sw_agg %>% as_tsibble() %>% 
  filter(is_aggregated(Country), !is_aggregated(Genus)) %>%
  autoplot(Metric) +
  theme(legend.position = "none")+
   scale_y_log10(limits = c(1,1e8), expand = c(0, 0))
```

```{r}

# this is a paragraph of aaepfkmsd and i hope it
fit <- sw_agg %>% 
  filter(YEAR<=2018) %>% 
  model(ETS = ETS(Metric),
        ARIMA = ARIMA(Metric)) %>% 
  reconcile(bu_E = bottom_up(ETS),
            ols_E = min_trace(ETS, method = "ols"),
            bu_A = bottom_up(ARIMA),
            ols_A = min_trace(ARIMA, method = "ols")
           # mint = min_trace(base, method = "mint_shrink")
           )
fc <- fit %>% forecast(h = "30 years")

fc %>% 
  filter(!is_aggregated(Country), is_aggregated(Genus)) %>% 
  filter(Region == "East Asia") %>% 
  filter(!(.model %in% c("ols_E", "ols_A"))) %>% 
  autoplot(
    sw_agg %>% filter(YEAR>=1980), alpha = 0.7, level = 70) +
  facet_wrap(vars(Country), scales = "free_y"
  )

fc %>% filter(is_aggregated(Region), is_aggregated(Genus)) %>% 
  accuracy(
    data = sw_agg, 
    measures = list(rmse = RMSE, mase = MASE)
  ) %>% 
  group_by(.model) %>% 
  summarise(rmse = mean(rmse), mase = mean(mase))
  
  
```


```{r}
# Examine for Stationarity
tc = "EuCA"
sp = "Phaeophyceae"

sw %>% filter(Location == tc, Genus == sp) %>% 
  autoplot(Metric)

t_sw <- sw %>% filter(Location == tc, Genus == sp)

t_sw %>% 
  mutate(diff_Metric = difference(difference(Metric))) %>% 
  features(diff_Metric, ljung_box, lag = 1)

lambda <- t_sw %>%  
  features(Metric, features = guerrero) %>% 
  pull(lambda_guerrero)

t_sw %>% 
gg_tsdisplay(difference(difference(box_cox(Metric, lambda))), plot_type = 'partial')


```


```{r Explore models}
##Safer to use stochastic trends for longer forecast horizons
t_sw_fit <- t_sw %>% 
  mutate(Metric = box_cox(Metric, lambda)) %>% 
  model(
  arima210 = ARIMA(Metric ~ pdq(2,1,0)),
    arima011 = ARIMA(Metric ~ pdq(0,1,1)),
    stepwise = ARIMA(Metric),
    search = ARIMA(Metric, stepwise = FALSE)
    
  )
## Want smallest AICc
glance(t_sw_fit) %>% slice_max(AICc, n = 1, with_ties = FALSE)

## Want all criteria met
t_sw_fit %>% 
  select(search) %>% 
  gg_tsresiduals()

## Want large p-value
augment(t_sw_fit) %>%
  filter(.model=='search') %>%
  features(.innov, ljung_box, lag = 10, dof = 3)

t_sw_fit %>%
  forecast(h=32) %>%
  filter(.model=='search') %>% 
  autoplot(t_sw)


t_sw <- t_sw %>% mutate(Metric = box_cox(Metric, lambda)) %>% 
  slice(-n()) %>% 
  stretch_tsibble(.init = 10) %>% 
  mutate(Metric = box_cox(Metric, lambda)) %>% 
  model(
    stepwise = ARIMA(Metric),
    ETS = ETS(Metric)
    
  ) %>% 
  forecast(h = 1) %>% 
  accuracy(t_sw)
```

```{r Fit models}
sw_gts <- sw %>% 
  aggregate_key(Location*Genus)

lambda <- sw %>% group_by(Genus, Location) %>% 
  features(Metric, features = guerrero) 
fit <- merge(sw, lambda, by = c("Genus", "Location")) %>% 
  mutate(Metric = box_cox(Metric, lambda_guerrero)) %>% 
  group_by(Genus, Location) %>% 
  nest() %>% 
  mutate(model = map(data, function(Metric) ARIMA(Metric, stepwise = FALSE)))

fcast <- fit %>% 
  mutate(fcast = map(model, predict))#forecast(h = "32 years", data = model)))
    
 


              
      arima210 = ARIMA(Metric ~ pdq(2,1,0), data = .x),
      arima011 = ARIMA(Metric ~ pdq(0,1,1),data = .x),
      stepwise = ARIMA(Metric, data = .x),
      search = ARIMA(Metric, stepwise = FALSE, data = .x)
      ))# %>% 
## Want smallest AICc
glance(t_sw_fit) %>% slice_max(AICc, n = 1, with_ties = FALSE))

fit <- sw %>% 
  model(ARIMA(box_cox(Metric, lambda))) # this is for ETS-> ~ error("M") + trend("A") + season("N")
            
t_fit <- fit %>% filter(Location == tc, Genus == sp)


# Compute forecasts
fcast <- forecast(fit, h = "32 years", level = 5) %>% 
  arrange(Genus, Location)

sw$lambda_guerrero


t_fcast <- fcast %>% filter(Location == tc, Genus == sp) 


t_fcast %>% 
autoplot() + 
  geom_line(aes(y = Metric, col = "Data", group = Location), data = t_sw)

t_fit %>% forecast(h = "32 years") %>% autoplot(t_sw)

```




```{r}
## Diagnostics
# Plot Residuals
aug <- augment(t_fit) 
autoplot(aug, .innov) +
  labs(title = "Plot of residuals")
aug %>%  features(.innov, box_pierce, lag = 10, dof =2)
aug %>% features(.innov, ljung_box, lag = 10, dof =2)

## Histogram
aug %>% ggplot(aes(x = .innov)) +
  geom_histogram() +
  labs(title = "Histogram of residuals")

t_fit %>% 
  gg_tsresiduals()

  
report(fit %>% filter(Location == tc, Genus == sp))
#components(fit %>% filter(Location == tc, Genus == sp)) %>%
 # autoplot() +
 # labs(title = "ETS(M,N,M) components")
  
```


```{r}


#fcast %>% filter(Location == tc) %>% 
#autoplot(sw) + 
#  theme(legend.position = "none") + 
#    scale_y_log10(limits = c(1,1e8), expand = c(0, 0))
ggplot(fcast %>% filter(Location == tc)
       ,
       aes(x=YEAR, y=Metric, fill = Location)) +
  autolayer(fcast %>% filter(Location == tc), alpha = 0.2, .vars = .mean, fcol = "black") +
  geom_line(data = sw %>% filter(Location == tc), aes(x = YEAR, y = Metric, group = Genus)) +
 #facet_wrap(~ Location, scales = "free") + 
    scale_y_log10(limits = c(1,1e8), expand = c(0, 0)) +
  theme(legend.position = "none") 
```

```{r}
fcast_2050 <- fcast %>% filter(YEAR == 2050)
```


```{r}
##Split countries into separate dataframes of Years by species  
listdata <- split(main_df, main_df$Country, drop = TRUE) 

listdata_val <- lapply(listdata, function(x) 
  as.data.frame(
    dcast(x, YEAR ~ Genus, 
          value.var = "VALUE", fun.aggregate = sum))) 

listdata_qua <- lapply(listdata, function(x) 
  as.data.frame(
    dcast(x, YEAR ~ Genus, 
          value.var = "QUANTITY", fun.aggregate = sum)))
```


```{r Choose _val or _qua}
##
listdata <- listdata_qua

```

```{r}
#### Remove Unwanted time-series from list of dataframes
## Remove time-series with fewer non-zero values than baseline (bsln)
#listdata <- lapply(listdata, function(x) {
# as.data.frame(x[, unlist((lapply(x, function(y) {sum(y > 0, na.rm = TRUE) #> bsln}))) ] )
#})

## Remove time-series with low production values; mean is below min_production (specified at start)
#listdata <- lapply(listdata, function(x) {
#  as.data.frame(x[, unlist((lapply(x, function(y) {mean(y, na.rm = TRUE) > min_production}))) ] )
#})

## Remove Countries with 2 or fewer cultivated species and countries with fewer reported years than bsln
#listdata <- listdata[sapply(listdata, function(x) ncol(x)) > 2]  
#listdata <- listdata[lapply(listdata, function(x) nrow(x)) > bsln]

```

```{r}
## In list of dataframes, set Years column to be row.names 
for (i in 1:length(listdata)) {
 row.names(listdata[[i]]) = listdata[[i]][,1]}

#listdata <- lapply(listdata, function(x) as.data.frame(x[,-1]))
```

```{r}
#### IDENTIFY SHOCKS
## FIT GAM MODELs 

models_ga <- listdata

models_ga <- lapply(listdata, function(x) {lapply(x, function(a,b)
  gam(a ~ lo(as.numeric(row.names(b)))),
  b = x)})
```

```{r}
## Fit LOESS Models (if desired)
models_ls <- listdata
models_ls <- lapply(listdata, function(x) {lapply(x, function(a,b) 
  loess(a ~ as.numeric(row.names(b)), 
        span = 0.6, na.action = "na.omit"), b=x)})
```



```{r Time-Series Visualization}

## Visualization of time-series for specific Case Studies
## ## this can be used to double-check that shocks are well-defined
## ## tc = Country name ; sp = Genus name

tc <- "China"
sp <- "Laminaria"

case_y = as.data.frame(
  cbind(
    as.numeric(
     row.names(
    listdata[[tc]][!is.na(
       listdata[[tc]][[sp]])
      ,])
   )
  , 
                    predict(models_ga[[tc]][[sp]] ) ))

names(case_y) <- c("YEAR", "Value")

case_x <- as.data.frame(cbind(as.numeric(row.names(listdata[[tc]][!is.na(listdata[[tc]][[sp]]),])), predict(models_ls[[tc]][[sp]]) ))
names(case_x) <- c("Year", "Value")


p <- ggplot() + 
  ## GAM Model Fit
  geom_line(data=case_y, aes(x=YEAR, y=Value), color='blue') + 
  ## LOESS Model Fit
  geom_line(data=case_x, aes(x=Year, y=Value), color='orange') + 
  ## DataPoints
  geom_line(data = listdata[[tc]], aes(x = as.numeric(row.names(listdata[[tc]])), 
                                     y = listdata[[tc]][[sp]]), na.rm = T) +
  xlim(1960,2050)
p
```

```{r}
prediction <- as_tsibble(as.data.frame(cbind(as.numeric(row.names(listdata[[tc]])),                            listdata[[tc]][[sp]])), index = "V1") %>% 
  rename("Year"= "V1" , "Amount" = "V2") 
prediction <- prediction %>% 
  model(
    #arima = ARIMA(Amount),
    ets = ETS(box_cox(Amount, 0.3))
    ) %>%
  forecast(h = "33 years", level = 5) 
p + geom_line(data = prediction, aes(x = Year, y = .mean, color = "red"))

growth <-  prediction %>%
  rename("Value" = ".mean") %>% 
  select(Year, Value) %>% 
  # first sort by year
  arrange(Year) %>%
  mutate(Diff_year = Year - lag(Year),  # Difference in time (just in case there are gaps)
         Diff_growth = Value - lag(Value), # Difference in route between years
         Rate_percent = (Diff_growth / Diff_year)/Value * 100) 

print(mean(growth[-1,]$Rate_percent))
###Need to get growth rate for each species for each country. Build into list.

```


```{r}
g_rates <- lapply(listdata, function(x) add_column(x, row.names(x), .before = 1)) %>% 
melt() %>% 
  rename("Year" = "row.names(x)", "Genus" = "variable", "Country" = "L1", "Value" = "value")  %>% 
  mutate(Country = as.factor(Country),
         Year = as.numeric(Year)) 
  

g_rates <- as.data.frame(g_rates)

```

>>>>>>> 253818d8d52818f80701ae40f76626ae36b73cad
